In [1]:
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize, linewidth=10000)

In [3]:
moves = {i: [np.array(a) for a in [[i,0], [0,-i], [0,i], [-i,0]]] for i in range(1, 9+1)}
moves

{1: [array([1, 0]), array([ 0, -1]), array([0, 1]), array([-1,  0])],
 2: [array([2, 0]), array([ 0, -2]), array([0, 2]), array([-2,  0])],
 3: [array([3, 0]), array([ 0, -3]), array([0, 3]), array([-3,  0])],
 4: [array([4, 0]), array([ 0, -4]), array([0, 4]), array([-4,  0])],
 5: [array([5, 0]), array([ 0, -5]), array([0, 5]), array([-5,  0])],
 6: [array([6, 0]), array([ 0, -6]), array([0, 6]), array([-6,  0])],
 7: [array([7, 0]), array([ 0, -7]), array([0, 7]), array([-7,  0])],
 8: [array([8, 0]), array([ 0, -8]), array([0, 8]), array([-8,  0])],
 9: [array([9, 0]), array([ 0, -9]), array([0, 9]), array([-9,  0])]}

In [382]:
moves = {i: [np.array(a) for a in [[i,0], [0,-i], [0,i], [-i,0]]] for i in range(1, 9+1)}
moves
def paint(arr, fr, mv):
    arr = arr.copy()
    d = abs(mv[0]) + abs(mv[1])
    #print(fr, mv)
    i,j = fr
    mi,mj = mv
    #print(i,j,mi,mj)
    if i+mi >= arr.shape[0] or j+mj >= arr.shape[1] or i+mi < 0 or j+mj < 0:
        return None, None
    gridnoland = ((arr+1)//2 != 0) if d > 1 else (arr != 0)
    gridnofly = arr >= 0
    gridnolandorfly = gridnoland + gridnofly
    theend = arr[i+mi, j+mj] == 0
    if mi:
        part = gridnofly[i+np.sign(mi):i+mi:np.sign(mi), j+mj]
        if gridnoland[i+mi,j+mj] or part.any():
            return None,None
        arr[i+np.sign(mi):i+mi+np.sign(mi):np.sign(mi), j+mj] = d
    if mj:
        part = gridnofly[i+mi, j+np.sign(mj):j+mj:np.sign(mj)]
        if gridnoland[i+mi,j+mj] or part.any():
            return None,None
        arr[i+mi, j+np.sign(mj):j+np.sign(mj)+mj:np.sign(mj)] = d
    arr[i+mi, j+mj] = 100
    if theend:
        arr[i+mi, j+mj] = 200
        return arr, None
    return arr, [i+mi, j+mj]

def explore(n, ex=None, pos=None, tot=None):
    if not n:
        return tot
    if ex is None:
        max_dist = (n*(n+1))//2
        mid = [max_dist, max_dist]
        ex = np.ndarray([max_dist+1+max_dist, max_dist+1+max_dist], dtype=int) * 0-1
    else:
        ex = ex.copy()
    pos = pos if pos is not None else mid
    ex[pos[0],pos[1]] = 99
    if tot is None:
        tot = ex.copy()
    for m in moves[n]:
        newarr, newpos = paint(ex, pos, m)
        if newarr is not None:
            tot[newarr!=0] = np.maximum(newarr[newarr!=0], tot[newarr!=0])
            #tot[newarr!=0] += newarr[newarr!=0]
        if newpos:
            tot = explore(n-1, ex=newarr, pos=newpos, tot=tot)
    return tot

t = explore(3)
#assert np.max(np.abs(t-t.T)) == 0
t

array([[ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  -1,  -1, 100,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  -1,  -1,   2,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1, 100,   2, 100,   2, 100,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1, 100,  -1,  -1,   3,  -1,  -1, 100,  -1,  -1,  -1],
       [ -1,  -1,  -1,   2,  -1,  -1,   3,  -1,  -1,   2,  -1,  -1,  -1],
       [ -1, 100,   2, 100,   3,   3,  99,   3,   3, 100,   2, 100,  -1],
       [ -1,  -1,  -1,   2,  -1,  -1,   3,  -1,  -1,   2,  -1,  -1,  -1],
       [ -1,  -1,  -1, 100,  -1,  -1,   3,  -1,  -1, 100,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1, 100,   2, 100,   2, 100,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  -1,  -1,   2,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  -1,  -1, 100,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1]])

In [383]:
other = np.array(
[[3,3,3,4,4,4,4,4,-8,0]
,[-8,-8,-1,-1,2,2,2,0,-8,-8]
,[-1,-1,-1,-1,4,-1,-1,-1,-1,-1]
,[-1,-1,-1,5,5,5,5,5,5,-1]
,[-1,-1,0,-1,5,-1,-1,-1,-1,-1]
,[-1,-1,-1,-1,-1,-1,-1,-1,-1,5]
,[-1,-1,-1,-1,-1,2,3,3,3,-1]
,[-1,-1,-1,-1,-1,2,-1,-1,-1,-1]
,[-8,-8,-1,-1,-1,1,1,-1,-8,-8]
,[0,-8,-1,-1,-1,-1,-1,-1,-8,0]])
t = explore(2, ex=other, pos=[7,0])
print(other)
print(t)

[[ 3  3  3  4  4  4  4  4 -8  0]
 [-8 -8 -1 -1  2  2  2  0 -8 -8]
 [-1 -1 -1 -1  4 -1 -1 -1 -1 -1]
 [-1 -1 -1  5  5  5  5  5  5 -1]
 [-1 -1  0 -1  5 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1  5]
 [-1 -1 -1 -1 -1  2  3  3  3 -1]
 [-1 -1 -1 -1 -1  2 -1 -1 -1 -1]
 [-8 -8 -1 -1 -1  1  1 -1 -8 -8]
 [ 0 -8 -1 -1 -1 -1 -1 -1 -8  0]]
[[  3   3   3   4   4   4   4   4  -8   0]
 [ -8  -8  -1  -1   2   2   2   0  -8  -8]
 [ -1  -1  -1  -1   4  -1  -1  -1  -1  -1]
 [ -1  -1  -1   5   5   5   5   5   5  -1]
 [ -1  -1   0  -1   5  -1  -1  -1  -1  -1]
 [100  -1  -1  -1  -1  -1  -1  -1  -1   5]
 [  2  -1  -1  -1  -1   2   3   3   3  -1]
 [ 99   2 100  -1  -1   2  -1  -1  -1  -1]
 [  2  -8  -1  -1  -1   1   1  -1  -8  -8]
 [200  -8  -1  -1  -1  -1  -1  -1  -8   0]]


In [384]:
def valid_pos(ex, count, pos):
    t = explore(count, ex=ex.copy(), pos=pos)
    return (t==200).any(), t
valid_pos(other, count=2, pos=[7,0])

(True,
 array([[  3,   3,   3,   4,   4,   4,   4,   4,  -8,   0],
        [ -8,  -8,  -1,  -1,   2,   2,   2,   0,  -8,  -8],
        [ -1,  -1,  -1,  -1,   4,  -1,  -1,  -1,  -1,  -1],
        [ -1,  -1,  -1,   5,   5,   5,   5,   5,   5,  -1],
        [ -1,  -1,   0,  -1,   5,  -1,  -1,  -1,  -1,  -1],
        [100,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,   5],
        [  2,  -1,  -1,  -1,  -1,   2,   3,   3,   3,  -1],
        [ 99,   2, 100,  -1,  -1,   2,  -1,  -1,  -1,  -1],
        [  2,  -8,  -1,  -1,  -1,   1,   1,  -1,  -8,  -8],
        [200,  -8,  -1,  -1,  -1,  -1,  -1,  -1,  -8,   0]]))

In [345]:
other = np.array([[0,-8,-1,4,4,4,4,4,-8,0]
,[-8,-8,-1,-1,2,2,2,0,-8,-8]
,[-1,-1,-1,-1,4,-1,-1,-1,-1,-1]
,[-1,-1,-1,5,5,5,5,5,5,-1]
,[-1,-1,0,-1,5,-1,-1,-1,-1,-1]
,[-1,-1,-1,-1,-1,-1,-1,-1,-1,5]
,[-1,-1,-1,-1,-1,3,3,3,3,-1]
,[-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]
,[-8,-8,-1,-1,-1,-1,0,-1,-8,-8]
,[0,-8,-1,-1,-1,-1,-1,-1,-8,0]])
t = explore(4, ex=other, pos=[3,3])
print(other)
print(t)

[[ 0 -8 -1  4  4  4  4  4 -8  0]
 [-8 -8 -1 -1  2  2  2  0 -8 -8]
 [-1 -1 -1 -1  4 -1 -1 -1 -1 -1]
 [-1 -1 -1  5  5  5  5  5  5 -1]
 [-1 -1  0 -1  5 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1  5]
 [-1 -1 -1 -1 -1  3  3  3  3 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-8 -8 -1 -1 -1 -1  0 -1 -8 -8]
 [ 0 -8 -1 -1 -1 -1 -1 -1 -8  0]]
[[  0  -8  -1   4   4   4   4   4  -8   0]
 [ -8  -8  -1  -1   2   2   2   0  -8  -8]
 [ -1  -1  -1  -1   4  -1  -1  -1  -1  -1]
 [ -1  -1  -1  99   5   5   5   5   5  -1]
 [100  -1   0   4   5  -1  -1  -1  -1  -1]
 [100 100  -1   4  -1  -1  -1  -1  -1   5]
 [  2  -1 100   4  -1   3   3   3   3  -1]
 [100   2 100 100   3   3 100   2 100 100]
 [  2  -8 100  -1  -1  -1   0  -1  -8  -8]
 [100  -8  -1  -1  -1  -1  -1  -1  -8   0]]


In [346]:
other = np.random.randint(low=0, high=5, size=[55,41]) // 3 * -7 -1
t = explore(7, ex=other, pos=[24,0])
t

array([[ -1,  -1,  -1,  -1,  -8,  -1,  -1,  -8,  -1,  -8,  -8,  -8,  -8,  -8,  -1,  -1,  -1,  -8,  -8,  -1,  -8,  -1,  -1,  -1,  -8,  -8,  -1,  -1,  -8,  -1,  -1,  -1,  -8,  -1,  -8,  -8,  -1,  -8,  -8,  -1,  -1],
       [ -1,  -8,  -1,  -8,  -1,  -1,  -1,  -8,  -8,  -8,  -8,  -1,  -8,  -1,  -1,  -1,  -1,  -1,  -8,  -1,  -8,  -1,  -1,  -8,  -8,  -1,  -8,  -8,  -8,  -8,  -1,  -8,  -8,  -1,  -1,  -8,  -8,  -8,  -8,  -8,  -8],
       [ -8,  -1,  -1,  -1,  -1,  -1,  -1,  -8,  -8,  -8,  -8,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -8,  -8,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -8,  -8,  -1,  -1,  -1,  -1,  -8,  -1,  -1,  -8,  -8],
       [ -1,  -8,  -1,  -1,  -1,  -1,  -8,  -8,  -1,  -1,  -1,  -1,  -8,  -1,  -8,  -1,  -8,  -1,  -8,  -1,  -8,  -1,  -8,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -8,  -8,  -1,  -1,  -1,  -8,  -1,  -8,  -8,  -8,  -1],
       [ -1,  -1,  -1,  -8,  -1,  -1,  -1,  -8,  -8,  -8,  -1,  -1,  -1,  -1,  -1,  -1,  -8,  -1,  -1,  -8,  -8,  -8,  -1,  -1,  -1,  -1,  -1,  

In [360]:
other = np.random.randint(low=0, high=5, size=[55,41]) // 3 * -7 -1
def valid_pos(ex, count, pos):
    if ex[pos[0], pos[1]] == 0:
        return True, None
    t = explore(count, ex=ex.copy(), pos=pos)
    return (t==200).any(), t
valid_pos(other, count=7, pos=[0,0])

(True,
 array([[ 99,   7,   7,   7,   7,   7,   7, 100,  -8,  -1,  -1,  -1,  -8,  -8,  -1,  -1,  -8,  -8,  -8,  -1,  -1,  -1,  -8,  -8,  -1,  -1,  -1,  -8,  -1,  -1,  -8,  -1,  -1,  -8,  -8,  -1,  -1,  -8,  -1,  -1,  -1],
        [ -1,  -8,  -1,  -8,  -8,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -8,  -1,  -1,  -8,  -8,  -8,  -1,  -1,  -1,  -8,  -1,  -8,  -8,  -1,  -1,  -1,  -8,  -8,  -1,  -1,  -1,  -1,  -1,  -1,  -8,  -8,  -1],
        [ -8,  -1,  -1,  -1,  -8,  -1,  -8,  -1,  -8,  -8,  -1,  -1,  -1,  -1,  -8,  -1,  -8,  -1,  -1,  -8,  -1,  -1,  -1,  -8,  -1,  -1,  -1,  -1,  -8,  -8,  -8,  -8,  -1,  -8,  -8,  -8,  -1,  -1,  -1,  -1,  -1],
        [ -1,  -1,  -8,  -8,  -8,  -8,  -1,  -8,  -8,  -1,  -1,  -1,  -1,  -8,  -1,  -1,  -8,  -8,  -1,  -8,  -1,  -1,  -8,  -1,  -1,  -8,  -8,  -1,  -8,  -1,  -8,  -8,  -1,  -1,  -1,  -8,  -8,  -8,  -8,  -8,  -8],
        [ -8,  -8,  -1,  -1,  -8,  -1,  -8,  -8,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -8,  -8,  -1,  -8,  -1,  -1,  -8,  -1,  -8,